language: java

branches:
  only:
  - master

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: build
      script: ./gradlew build

    - stage: deploy
      script: sh deploy.sh

cache:
  - $HOME/.cache/pip
  - oraclejdk8